language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
install: python setup.py install && pip install -r ./requirements-tests.txt
# command to run tests, e.g. python setup.py test
script: py.test tests
